services:
  - type: web
    name: ai-coder
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: OPENAI_API_KEY
        sync: false